name: AutenticoServer
description: Anti account spoofing solution.
author: wolfarmoon
main: dev.wolfarmoon.autenticoserver.AutenticoServer
version: 0.0.1
url: https://github.com/wolfarmoon/autentico-server

commands:
  test:
    aliases: []
    description: ""